#!/usr/bin/env bash
# Fixes a web server to run Nginx as the nginx user listening on port 8080.
# change config file mode : adding writing previlige
chmod 644 /etc/nginx/nginx.conf
# update config files
sed -i "1i user nginx;" /etc/nginx/nginx.conf
# forwarding port 80 to 8080
sed -i 's/80/8080/' /etc/nginx/sites-enabled/default
# prevent apache2 from taking port 8080 by killing it
pkill -f apache2
sudo -u nginx service nginx restart
